name: mentorship-ci

on:
  pull_request:
    branches: [ "main" ]
    types: [ closed ] # Trigger when a PR is closed

jobs:
  build:
    # This 'if' ensures the job ONLY runs if the PR was merged, 
    # not just closed/cancelled.
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn clean package
